export const routing = {
  LOGIN: 'ingresar',
  REGISTER: 'registrarse',
  PROFILE: 'perfil',
  PROFILE_INTRO: 'perfil/intro',
  PROFILE_AVATAR: 'perfil/avatar',
  PROFILE_COMPLETE: 'perfil/completar',
  ON_BOARDING_TEST: 'perfil/on-boarding',
  HOME: 'home',
  CAREER: 'carrera',
  PERSONALITY: 'carrera/personalidad',
  PERSONALITY_TEST: 'carrera/personalidad/test',
  PERSONALITY_FINISH: 'carrera/personalidad/finalizado',
  PERSONALITY_RESULT: 'carrera/personalidad/resultado',
  IDEAL_CAREER: 'carrera/ideal',
  IDEAL_CAREER_PART_1: 'carrera/ideal/intereses',
  IDEAL_CAREER_PART_2: 'carrera/ideal/habilidades',
  IDEAL_CAREER_PART_3: 'carrera/ideal/automanejo',
  CAREER_EXPLORER: 'carrera/explorer',
};
